### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by NoorBek-InfTech** [roman-neuhauser/shellsql#1]
Preparing...
Cloning shellsql build files...
Checking shellsql dependencies...
Resolving dependencies...
Checking inter-conflicts...

Building shellsql...
==> ERROR: Missing package() function in /var/tmp/pamac-build-noorbek/shellsql/PKGBUILD

it was from AUR, i cannot install it even from terminal(yay -S shellsql...) and tried to git clone ...

**Comment by roman-neuhauser** [comment]
bug downstream of shellsql: in your /var/tmp/pamac-build-noorbek/shellsql/PKGBUILD
